AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Starter

Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Parameters:
  StageName:
    Type: String
    Default: prod
  LambdaTimeout:
    Type: Number
    Default: 30
    MinValue: 5
    MaxValue: 300
    Description: "Maximum Lambda execution time in seconds"
  LambdaMemorySize:
    Type: String
    Default: 1024
    AllowedValues: [ 128,192,256,320,384,448,512,576,640,704,768,832,896,960,1024,1088,1152,1216,1280,1344,1408,1472,1536 ]

Resources:
  StarterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaInvokeFunction'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
        - PolicyName: 'LogFull'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*"
  StarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StarterFunction
      CodeUri: ./
      Handler: handlers/index.handler
      Runtime: nodejs14.x
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Role:  !GetAtt StarterLambdaRole.Arn
      Events:
        GenerateEvent:
          Type: Api
          StageName: !Ref StageName
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  StarterFunction:
    Description: "Starter Analytics Lambda Function ARN"
    Value: !GetAtt StarterFunction.Arn
  StarterLambdaRole:
    Description: "Implicit IAM Role created for Starter Analytics function"
    Value: !GetAtt StarterLambdaRole.Arn